"""empty message

Revision ID: 801d5d5028d9
Revises: 
Create Date: 2021-08-19 05:00:29.373778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801d5d5028d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinputs')
    # ### end Alembic commands ###
